version: 3
workdir: internal
excludeFiles:
  - "^.*_test\\.go$"

allow:
  depOnAnyVendor: true

components:
  api:        { in: infrastructure/api/** }
  services:   { in: services/** }
  db:         { in: infrastructure/db/** }
  users:      { in: users }
  config:     { in: config/** }
  pagination: { in: pagination }

commonComponents:
  - users
  - config
  - pagination

deps:
  api:
    mayDependOn:
      - api
      - services
      - config
  services:
    mayDependOn:
      - db
  db:
    mayDependOn:
      - db
      - config
