---
extends:
  - "spectral:oas"
  - "spectral:asyncapi"
  - "spectral:arazzo"
  - "https://unpkg.com/@apisyouwonthate/style-guide@1.5.0/dist/ruleset.js"
rules:
  # Disabling Security check because this is a template
  no-security-schemes-defined: off
