#!/bin/sh

vale --glob '*.{md,rst}' --glob '!styles/*' *
markdownlint-cli2 --fix ./**/*.md
keep-sorted ./.golangci.yml ./resources/openapi.yml
# Stage any changes made by the linter
git add -u
codespell .
yamllint .
hadolint Dockerfile
go test ./...
